#! /bin/sh

TGT="$1"
if test "$1" = ""; then
  echo "usage: $0 file"
  exit 1
fi
if test -f "$TGT" ; then
  echo "file $TGT already exists"
  exit 1
fi

avconv -ac 1 -f pulse -i default -r 10 -s 1024x768 -f x11grab -i "$DISPLAY" -f webm - > $TGT
