#! /bin/sh

TGT="$1"
if test "$1" = ""; then
  echo "usage: $0 file"
  exit 1
fi
if test -f "$TGT" ; then
  echo "file $TGT already exists"
  exit 1
fi

#avconv -ac 1 -f alsa -i default -r 10 -s 1024x768 -f x11grab -i "$DISPLAY" -f webm - > $TGT
pavucontrol &

gst-launch-1.0 \
    matroskamux streamable=true name=mux ! filesink location="$TGT" \
    \
    ximagesrc \
    ! videoscale \
    ! 'video/x-raw,width=(int)1024,height=(int)768,framerate=(fraction)5/1' \
    ! videoconvert \
    ! queue \
    ! theoraenc \
    ! mux. \
    \
    pulsesrc \
    ! queue \
    ! audioconvert \
    ! vorbisenc \
    ! mux. \
