#! /bin/sh

TGT="$1"
if test "$1" = ""; then
  echo "usage: $0 file.mkv"
  exit 1
fi
if test -f "$TGT" ; then
  echo "file $TGT already exists"
  exit 1
fi

QARGS="max-size-bytes=1000000000 max-size-time=0"
pavucontrol &
guvcview -o > /dev/null 2&>1 &

for i in 6 5 4 3 2 1; do
	echo "starting stream in $i..."
	sleep 1
done

gst-launch-1.0 --eos-on-shutdown \
  v4l2src device="/dev/video0" \
  ! 'image/jpeg,width=(int)1920,height=(int)1080,framerate=(fraction)15/1' \
  ! tee name=jpeg-video-t \
  \
  jpeg-video-t. \
  ! queue $QARGS \
  ! jpegdec \
  ! videoscale \
  ! 'video/x-raw,width=(int)640,height=(int)360' \
  ! autovideosink \
  \
  jpeg-video-t. \
  ! queue $QARGS \
  ! matroskamux name=mux streamable=true \
  ! queue $QARGS \
  ! filesink location="$TGT" \
  \
  pulsesrc \
  ! 'audio/x-raw,rate=(int)22050' \
  ! audiorate \
  ! mux.audio_0

