#! /bin/sh

TGT="$1"
if test "$1" = ""; then
  echo "usage: $0 file.mkv"
  exit 1
fi
if test -f "$TGT" ; then
  echo "file $TGT already exists"
  exit 1
fi

export GST_DEBUG=4
gst-launch-1.0 --eos-on-shutdown \
  v4l2src device=/dev/video0 name=vsrc \
  ! 'image/jpeg,width=(int)1280,height=(int)720,framerate=(fraction)30/1' \
  ! tee name=jpeg-video-t \
  \
  jpeg-video-t. \
  ! queue \
  ! jpegdec \
  ! videoscale \
  ! 'video/x-raw,width=(int)640,height=(int)360' \
  ! autovideosink \
  \
  jpeg-video-t. \
  ! queue \
  ! matroskamux name=mux \
  ! queue \
  ! filesink location="$TGT" \
  \
  alsasrc device="default" \
  ! 'audio/x-raw,rate=(int)24000' \
  ! mux.

# to change:
# - alsa device
# - resolution
