#! /usr/bin/env python
import gobject
import sys
gobject.threads_init()

from dbus.mainloop.glib import DBusGMainLoop
loop = DBusGMainLoop(set_as_default=True)

import dbus
bus = dbus.SessionBus()
oku_name, = [unicode(s) for s in bus.list_names() if "okular" in s]
okular = bus.get_object(oku_name, '/okular')
iface = dbus.Interface(okular, 'org.kde.okular')

from time import sleep, time
while True:
    print time(), iface.currentPage()
    sys.stdout.flush()
    sleep(1)
