#! /usr/bin/env python

import sys
slides_lines = [
        l.split() for l in open(sys.argv[1], "rt").readlines() 
        if l.strip() and len(l.split()) == 2]
slides_lines = [(float(t), int(nr)) for t, nr in slides_lines]

result = []
last_slide = None
for t, nr in slides_lines:
    if last_slide != nr:
        result.append((nr, t))
        last_slide = nr

from json import dumps
print dumps(result)

